#import "main.asm"

.disk [filename="120hz.d64", name="SYSTEM BEEPS", id="2021!" ] {
        [ name="SYSTEM BEEPS",     type="prg", segments="MAIN"                   ],
        [ name="----------------", type="rel"                                    ],
        [ name="SYS",              type="prg", prgFiles="res/songs-sid/sys.lz77" ],
        [ name="TMB",              type="prg", prgFiles="res/songs-sid/tmb.lz77" ],
        [ name="BTL",              type="prg", prgFiles="res/songs-sid/btl.lz77" ],
        [ name="MNC",              type="prg", prgFiles="res/songs-sid/mnc.lz77" ],
        [ name="HST",              type="prg", prgFiles="res/songs-sid/hst.lz77" ],
        [ name="BAD",              type="prg", prgFiles="res/songs-sid/bad.lz77" ],
        [ name="DLD",              type="prg", prgFiles="res/songs-sid/dld.lz77" ],
        [ name="HSH",              type="prg", prgFiles="res/songs-sid/hsh.lz77" ],
        [ name="FLO",              type="prg", prgFiles="res/songs-sid/flo.lz77" ],
        [ name="PXL",              type="prg", prgFiles="res/songs-sid/pxl.lz77" ],
        [ name="SSD",              type="prg", prgFiles="res/songs-sid/ssd.lz77" ],
        [ name="LED",              type="prg", prgFiles="res/songs-sid/led.lz77" ],
        [ name="CLO",              type="prg", prgFiles="res/songs-sid/clo.lz77" ],
        [ name="TXR",              type="prg", prgFiles="res/songs-sid/txr.lz77" ],
        [ name="SRV",              type="prg", prgFiles="res/songs-sid/srv.lz77" ],
        [ name="STF",              type="prg", prgFiles="res/songs-sid/stf.lz77" ],
        [ name="ASF",              type="prg", prgFiles="res/songs-sid/asf.lz77" ],
        [ name="RUN",              type="prg", prgFiles="res/songs-sid/run.lz77" ],
        [ name="MYM",              type="prg", prgFiles="res/songs-sid/mym.lz77" ],
        [ name="SQW",              type="prg", prgFiles="res/songs-sid/sqw.lz77" ],
        [ name="FIN",              type="prg", prgFiles="res/songs-sid/fin.lz77" ],
        [ name="COY",              type="prg", prgFiles="res/songs-sid/coy.lz77" ],
        [ name="AON",              type="prg", prgFiles="res/songs-sid/aon.lz77" ],
}
